[package]
name = "rust_bank"
version = "0.1.0"
edition = "2021"

[dependencies]
bank_protocol = { path = "./bank_protocol" }
bank_server = { path = "./bank_server" }
bank_core = { path = "./bank_core" }

